### PR TITLE
Fix tests and issue #2 (by using class name instead of test filename for *.approved.txt file)

### PR DESCRIPTION
**Pull request by maxalbert**
I just stumbled upon ApprovalTests and am really keen to try it out for a couple of my projects. Kudos for making the Python port available!

When I ran the tests locally they failed. The reason (apart from a hard-coded value for "BeyondCompare4") was the same as in issue #2: the `Namer` would use `__main__` as the first component instead of the name of the test class. This PR fixes that, and adjusts the tests accordingly.

Btw, I'm interested in getting ApprovalTests to work smoothly with `py.test`, in particular for use cases where the test is defined in a simple function instead of a class method. Obviously in this situation the class name is undefined, so ApprovalTests may need to fall back to a more flexible naming scheme. Maybe it could use `filename.class_name.method_name` if the test is in class method and `filename.function_name` if it is in a regular function? I'll have a play, but if you have any ideas I'd be happy to hear them. I'll probably open a separate issue for this discussion once I have a bit more experience with ApprovalTests. Thanks!

### CODE REVIEW

**Comment by maxalbert** [comment]
The Travis build failed at first (due to a strange "rake" error, presumably because Travis didn't correctly detect that this is a Python project). I have added a simple `.travis.yml` file to solve this issue, which also installs `meld` because the tests need a diff/merge tool.

**Comment by jamesrcounts** [comment]
Thank you for looking into travis.  I will checkout these changes later tonight.

**Comment by isidore** [comment]
@maxalbert I'd be happy to pair with you on this stuff, but this week is crazy with the agile tech conf and onsite in florida after. but week after that would be good for me. connect via email/twitter or skype and setup a date.

**Comment by jamesrcounts** [comment]
LGTM, thanks!

**Pull request merged**
