### PR TITLE
Adds support for pypy

### LINKED ISSUE #29: Approval Tests with pypy
I have [pypy](https://github.com/squeaky-pl/portable-pypy#latest-python-35-release) installed and I would like to run approval tests with pypy. When I have simple example like this: 
```
import unittest

from approvaltests.approvals import verify
from approvaltests.reporters.generic_diff_reporter_factory import GenericDiffReporterFactory


class DummyTest(unittest.TestCase):

    def test_dummy(self):
        factory = GenericDiffReporterFactory()
        reporter = factory.get_first_working()
        verify('foobar', reporter)


if __name__ == "__main__":
        unittest.main()
```
And when I run it like this: `pypy3.5 dummy_test.py`, then I get error like this: 
```

mv -f /home/username/apps/pypy3.5-6.0.0-linux_x86_64-portable/lib-python/3/unittest/DummyTest.__call__.received.txt /home/username/apps/pypy3.5-6.0.0-linux_x86_64-portable/lib-python/3/unittest/DummyTest.__call__.approved.txt


E
======================================================================
ERROR: test_dummy (__main__.DummyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "utest/test/keywords/test_dummy.py", line 12, in test_dummy
    verify('foobar', reporter)
  File "/home/godtdd/apps/pypy3.5-6.0.0-linux_x86_64-portable/site-packages/approvaltests/approvals.py", line 35, in verify
    verify_with_namer(data, get_default_namer(), reporter)
  File "/home/godtdd/apps/pypy3.5-6.0.0-linux_x86_64-portable/site-packages/approvaltests/approvals.py", line 44, in verify_with_namer
    raise ApprovalException(error)
approvaltests.approval_exception.ApprovalException: 'Approval Mismatch'

----------------------------------------------------------------------
Ran 1 test in 0.057s

``` 
It looks like that in pypy the namer.py [get_base_name](https://github.com/approvals/ApprovalTests.Python/blob/master/approvaltests/core/namer.py#L27) does not work correctly and it returns something that refers to unitest framework installed in pypy. In my case it is something like this: `'/home/username/apps/pypy3.5-6.0.0-linux_x86_64-portable/lib-python/3/unittest/DummyTest.__call__'` When I run the same test with Python 2.7 or 3.6 the `get_base_name` works correctly and returns in my case this `u'/home/username/workspace/SeleniumLibrary/utest/test/keywords/approved_files/DummyTest.test_dummy'`. 

By debugging issue little further, it looks like [is_test_method](https://github.com/approvals/ApprovalTests.Python/blob/master/approvaltests/core/namer.py#L67) does not work correctly with pypy and it returns `True` also for pypy unitest frames. I was wondering could it be fixed in the [get_test_frame](https://github.com/approvals/ApprovalTests.Python/blob/master/approvaltests/core/namer.py#L59) method. It currently looks like this: 
``` 
    def get_test_frame(self, caller):
        frameNumber = 1
        for index, frame in enumerate(caller):
            if self.is_test_method(frame):
                frameNumber = index

        return frameNumber
``` 
and could it be changed like this:
```
    def get_test_frame(self, caller):
        frameNumber = 1
        for index, frame in enumerate(caller):
            if self.is_test_method(frame):
                return index
        raise AssertionError('Test frame not found.')
```
At least it fixes my problem, but my knowledge on ApprovalTests is limited and I do not know is there a good reason to loop trough all frames.

### PR DESCRIPTION
**Pull request by aaltat**
Fixes #29

### CODE REVIEW

**Comment by aaltat** [comment]
Good ideas and I don't have any better names available. I will do the changes.

**Comment by aaltat** [comment]
Sorry for long delay, but here are the requested enhancements.

**Comment by isidore** [comment]
This looks ok. Would be good to have *supported* by dynamic, but good enough for now. Would also be good to get travis setup. @tdpreece Do you mind running test and committing this on success?
Also, would be good to make a test for this.
to Do that we probably need to setup the namer in a bit of a factory pattern, so we can remove/mock out the test framework to get an unsupported error

**Comment by tdpreece** [comment]
Yep, will run tests and commit on success.

On 6 Aug 2018 20:01, "Llewellyn Falco" <notifications@github.com> wrote:

This looks ok. Would be good to have *supported* by dynamic, but good
enough for now. Would also be good to get travis setup. @tdpreece
<https://github.com/tdpreece> Do you mind running test and committing this
on success?
Also, would be good to make a test for this.
to Do that we probably need to setup the namer in a bit of a factory
pattern, so we can remove/mock out the test framework to get an unsupported
error

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/approvals/ApprovalTests.Python/pull/30#issuecomment-410817272>,
or mute the thread

**Comment by tdpreece** [comment]
@aaltat Thanks again for the PR.  This change has been pushed to pypi in version (see approvaltests 0.2.3)

**Comment by aaltat** [comment]
Oh cool. Thanks for the quick release.

**Pull request merged**
