### PR TITLE
Fix missing approvaltests.reporters submodule when installing package

### PR DESCRIPTION
**Pull request by sashdown**
setup.py is missing approvaltests.reporters submodule, causing "setup.py build" to build an incomplete package

### CODE REVIEW

**Comment by tdpreece** [comment]
Thanks for the pull request :)

I think using find_packages is the right thing to do here.

I guess the tests didn't break because `reporters` would be available from the root dir, which is where we're running the tests from.  
To ensure that the package installed by tox is tested (and not the original package in the root dir) we could change the dir that the tests are run in using the `changedir` tox setting or put the `approvaltests` package in a `src` dir so it's not available when running the tests from the root dir.

**Comment by jamesrcounts** [comment]
Does this break compat with python27?  Looks like all the python27 tests failed on TravisCI.

**Comment by tdpreece** [comment]
I think the build was already broken.  I'm not sure why it's passing for 3.4 ....
There was an attempt to fix the build in pull request #17, https://github.com/approvals/ApprovalTests.Python/pull/17, though I don't think the fix in pull request #17 is complete (see my comment there).

**Comment by jamesrcounts** [comment]
Can you merge or rebase on master now that we have merged #17?  This may fix your build and allow us to accept your PR.

**Comment by sashdown** [comment]
Done -the build is  passing now.

**Comment by jamesrcounts** [comment]
pushed v0.1.14 to pypi

**Pull request merged**
